chore: partial conversion to zsh

diff --git a/fadd b/fadd
--- a/fadd
+++ b/fadd
@@ -1,5 +1,8 @@
-#!/usr/bin/env bash
-#
+#!/usr/bin/env zsh
+
+0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
+0="${${(M)0:#/*}:-$PWD/$0}"
+
 # Desc: stage the selected file to git bare repo
 #
 # @params
@@ -12,23 +15,26 @@
 #   -f|--file: select a file in PWD to stage
 #   -d|--dir: select a directory in PWD to stage
 
-set -ef
+emulate -LR zsh
+setopt warncreateglobal noshortloops
 
-mydir="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
-source "${mydir}"/fgit_helper.sh
+local mydir; mydir=${0:h:A}
+builtin source ${mydir}/fgit_helper
 
-usage() {
-  echo -e "Usage: fadd [-h] [-f] [-d] ...
+function usage() {
+  builtin print -P -- "\
+%F{1}%BUsage%f%b:
+  %F{2}fadd%f [%F{13}-h%f] [%F{13}-f%f] [%F{13}-d%f] ...
 
 Select files/directories or modified files through fzf.
 Stage the selected file to the dotfile gitbare repo.
 
-Default: list all modified files and stage the selected files.
+%F{4}Default%f: list all modified files and stage the selected files.
 
-Optional arguments:
-  -h, --help\t\tshow this help message and exit.
-  -f, --file\t\tselect files in current directory and stage the selected files.
-  -d, --dir\t\tselect folders in current directory and stage the selected folders."
+%F{1}%BOptions%f%b:
+  %F{13}-h%f, %F{13}--help%f    Show this help message and exit
+  %F{13}-f%f, %F{13}--file%f    Select files in current directory and stage the selected files
+  %F{13}-d%f, %F{13}--dir%f     Select folders in current directory and stage the selected folders"
 }
 
 #######################################
@@ -37,36 +43,32 @@ Optional arguments:
 #   $1: array of files to stage
 #######################################
 
-stage_file() {
+function stage_file() {
   local -a files && files=("$@")
-  [[ "${#files[@]}" -eq 0 ]] && { printf "%s" "$(tput setaf 1)Nothing added$(tput sgr0)"; exit 1; }
-  git add "${files[@]}"
+  (( $#files == 0 )) && { print -Pr -- "%F{1}Nothing added%f"; exit 1; }
+  command git add "${files[@]}"
 }
 
-stage_type="modified"
-typeset -a selected_files && selected_files=()
+local stage_type="modified"
+local -a selected_files
 
-while [[ "$#" -gt 0 ]]; do
+while (( $# )) {
   case "$1" in
-    -f|--file) stage_type="file"; shift ;;
-    -d|--dir) stage_type="dir";   shift ;;
-    -h|--help) usage && exit 0 ;;
-    *) echo "Invalid option: $1" >&2 && usage && exit 1 ;;
+    (-f|--file) stage_type="file"; shift ;;
+    (-d|--dir)  stage_type="dir";  shift ;;
+    (-h|--help) usage && exit 0 ;;
+    (*)         print::error "Invalid option: $1" && { usage; exit 1 } ;;
   esac
-done
+}
 
-while IFS= read -r line; do
-  selected_files+=("${line}")
-done < <(
-  if [[ "${stage_type}" == "file" ]]; then
-    search_file 'f'
-  elif [[ "${stage_type}" == "dir" ]]; then
-    search_file 'd'
-  else
-    get_modified_file "select files to stage" "unstaged"
-  fi
-)
+if [[ $stage_type = file ]] {
+  selected_files=( ${(@f)"$(search_file f)"} )
+} elif [[ $stage_type = dir ]] {
+  selected_files=( ${(@f)"$(search_file d)"} )
+} else {
+  selected_files=( ${(@f)"$(get_modified_file 'Select files to stage' 'unstaged')"} )
+}
 
-stage_file "${selected_files[@]}"
+stage_file "$selected_files[@]"
 
-[[ "${#selected_files[@]}" -ne 0 ]] && git status -sb
+(( $#selected_files )) && command git status -sb
diff --git a/fcheckout b/fcheckout
--- a/fcheckout
+++ b/fcheckout
@@ -1,5 +1,8 @@
-#!/usr/bin/env bash
-#
+#!/usr/bin/env zsh
+
+0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
+0="${${(M)0:#/*}:-$PWD/$0}"
+
 # Desc: checkout files/commit/branches using fzf
 #
 # @params
@@ -16,77 +19,79 @@
 #   -b|--branch: search branch and checkout branch
 #   -c|--commit: search commit and checkout commit
 
-set -ef
+emulate -LR zsh
+setopt warncreateglobal noshortloops
 
-mydir="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
-source "${mydir}"/fgit_helper.sh
+local mydir; mydir=${0:h:A}
+builtin source ${mydir}/fgit_helper
 
-usage() {
-  echo -e "Usage: fcheckout [-h] [-s] [-b] [-c] [-y] ...
+function usage() {
+  builtin print -P -- "\
+%F{1}%BUsage%f%b:
+  %F{2}fcheckout%f [%F{13}-h%f] [%F{13}-s%f] [%F{13}-b%f] [%F{13}-c%f] [%F{13}-y%f] ...
 
-Select files/commit/branch through fzf and checkout the selected objects.
-Files: checkout the version in HEAD or in a specific commit (reset files content back to the selected commit).
-Branch: switch to the selected branch.
-Commit: switch to a specific commit.
+%F{11}Select%f files/commit/branch through fzf and checkout the selected objects.
+%F{11}Files%f: checkout version in %F{2}HEAD%f or in a specific commit (reset file content to commit).
+%F{11}Branch%f: switch to the selected branch.
+%F{11}Commit%f: switch to a specific commit.
 
-Default: list all modified files and reset selected files back to HEAD.
+%F{4}Default%f: list all modified files and reset selected files back to HEAD.
 
-Optional arguments:
-  -h, --help\t\tshow this help message and exit.
-  -s, --select\t\tlist all tracked files and select a commit to checkout the selected files.
-  -b, --branch\t\tlist all branch and checkout/switch the selected branch.
-  -c, --commit\t\tlist all commits and checkout selected commit.
-  -y, --yes\t\tacknowledge all actions that will be taken and skip confirmation."
+%F{1}%BOptions%f%b:
+  %F{13}-h%f, %F{13}--help%f    Show this help message and exit
+  %F{13}-s%f, %F{13}--select%f  List all tracked files and select a commit to checkout the selected files
+  %F{13}-b%f, %F{13}--branch%f  List all branch and checkout/switch the selected branch
+  %F{13}-c%f, %F{13}--commit%f  List all commits and checkout selected commit
+  %F{13}-y%f, %F{13}--yes%f     Acknowledge all actions that will be taken and skip confirmation"
 }
 
+local -a selected_files
+local action_type confirm selected_commit selected_branch
 action_type="modified"
-typeset -a selected_files && selected_files=()
-confirm=""
-selected_commit=""
-selected_branch=""
 
-while [[ "$#" -gt 0 ]]; do
+while (( $# )) {
   case "$1" in
-    -s|--select) action_type="select"; shift ;;
-    -b|--branch) action_type="branch"; shift ;;
-    -c|--commit) action_type="commit"; shift ;;
-    -y|--yes) confirm="y";             shift ;;
-    -h|--help) usage && exit 0 ;;
-    *) echo "Invalid option: $1" >&2 && usage && exit 1;;
+    (-s|--select) action_type="select"; shift ;;
+    (-b|--branch) action_type="branch"; shift ;;
+    (-c|--commit) action_type="commit"; shift ;;
+    (-y|--yes)    confirm="y";             shift ;;
+    (-h|--help)   usage && exit 0 ;;
+    (*)           print::error "Invalid option: $1" && { usage; exit 1 } ;;
   esac
-done
+}
 
-if [[ "${action_type}" == "branch" ]]; then
-  # checkout branch
-  selected_branch=$(get_branch 'select a branch to checkout')
-  [[ -z "${selected_branch}" ]] && exit 1
-  git checkout "${selected_branch}"
-elif [[ "${action_type}" == "commit" ]]; then
-  # checkout commit
-  selected_commit=$(get_commit 'select a commit to checkout')
+if [[ "$action_type" = branch ]]; then
+  # Checkout branch
+  selected_branch=$(get_branch 'Select a branch to checkout')
+  [[ -z "$selected_branch" ]] && exit 1
+  command git checkout "${selected_branch}"
+
+elif [[ "$action_type" = "commit" ]]; then
+  # Checkout commit
+  selected_commit=$(get_commit 'Select a commit to checkout')
   [[ -z "${selected_commit}" ]] && exit 1
-  git checkout "${selected_commit}"
-elif [[ "${action_type}" == "modified" ]]; then
-  # checkout modified file back to version in HEAD
-  while IFS= read -r line; do
-    selected_files+=("${line}")
-  done < <(get_modified_file 'select files to checkout version in HEAD')
-  [[ "${#selected_files[@]}" -eq 0 ]] && exit 1
-  [[ -z "${confirm}" ]] && echo "(dryrun) git checkout --" "${selected_files[@]}"
-  [[ -z "${confirm}" ]] && confirm=$(get_confirmation "Confirm?")
-  [[ "${confirm}" != 'y' ]] && exit 1
-  git checkout -- "${selected_files[@]}"
-elif [[ "${action_type}" == "select" ]]; then
-  # checkout selected files to a selected commit
-  while IFS= read -r line; do
-    selected_files+=("${line}")
-  done < <(get_git_file 'select files to checkout to previous commit')
-  [[ "${#selected_files[@]}" -eq 0 ]] && exit 1
-  # continue select a commit and then checkout the file back to the selected commit
+  command git checkout "${selected_commit}"
+
+elif [[ "$action_type" = modified ]]; then
+  # Checkout modified file back to version in HEAD
+  selected_files=( ${(@f)"$(get_modified_file 'select files to checkout version in HEAD')"} )
+  (( $#selected_files )) || exit 1
+  [[ -z "$confirm" ]] && \
+    builtin print -P "(%F{3}dryrun%f) %F{2}git%f checkout --" "${selected_files[@]}"
+  [[ -z "$confirm" ]] && confirm=$(get_confirmation "Confirm?")
+  [[ "$confirm" != y ]] && exit 1
+  command git checkout -- "$selected_files[@]"
+
+elif [[ "$action_type" = select ]]; then
+  # Checkout selected files to a selected commit
+  selected_files=( ${(@f)"$(get_git_file 'select files to checkout to previous commit')"} )
+  (( $#selected_files )) || exit 1
+  # Continue select a commit and then checkout the file back to the selected commit
   selected_commit=$(get_commit 'select the target commit' "${selected_files[@]}")
-  [[ -z "${selected_commit}" ]] && exit 1
-  [[ -z "${confirm}" ]] && echo "(dryrun) git checkout ${selected_commit} --" "${selected_files[@]}"
-  [[ -z "${confirm}" ]] && confirm=$(get_confirmation "Confirm?")
-  [[ "${confirm}" != 'y' ]] && exit 0
-  git checkout "${selected_commit}" "${selected_files[@]}"
+  [[ -z "$selected_commit" ]] && exit 1
+  [[ -z "$confirm" ]] && \
+    builtin print -P "(%F{3}dryrun%f) %F{2}git%f checkout ${selected_commit} --" "${selected_files[@]}"
+  [[ -z "$confirm" ]] && confirm=$(get_confirmation "Confirm?")
+  [[ "$confirm" != y ]] && exit 0
+  command git checkout "$selected_commit" "$selected_files[@]"
 fi
diff --git a/fedit b/fedit
--- a/fedit
+++ b/fedit
@@ -1,5 +1,8 @@
-#!/usr/bin/env bash
-#
+#!/usr/bin/env zsh
+
+0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
+0="${${(M)0:#/*}:-$PWD/$0}"
+
 # Desc: interactive menu to choose file/commit to edit
 #
 # @params
@@ -13,51 +16,51 @@
 #   -c|--commit: edit commit using interactive rebase
 #   -h|--help: show helpe message and exit
 
-set -ef
+emulate -LR zsh
+setopt warncreateglobal noshortloops
 
-mydir="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
-source "${mydir}"/fgit_helper.sh
+local mydir; mydir=${0:h:A}
+builtin source ${mydir}/fgit_helper
 
-usage() {
-  echo -e "Usage: fedit [-h] [-m] [-c] ...
+function usage() {
+  builtin print -P "\
+%F{1}%BUsage%f%b:
+  %F{2}fedit%f [%F{13}-h%f] [%F{13}-m%f] [%F{13}-c%f] ...
 
-Select files/commits through fzf and edit selected files/commits in EDITOR.
+%F{11}Select%f files/commits through fzf and edit selected files/commits in EDITOR.
 
-Default: list all tracked dotfiles and edit the selected files.
+%F{4}Default%f: list all tracked dotfiles and edit the selected files.
 
-Optional arguments:
-  -h, --help\t\tshow this help message and exit.
-  -m, --modified\tonly list and edit selected modified files.
-  -c, --commit\t\tlist commit and edit the selected commit through interactive rebase."
+%F{1}%BOptions%f%b:
+  %F{13}-h%f, %F{13}--help%f      Show this help message and exit
+  %F{13}-m%f, %F{13}--modified%f  Only list and edit selected modified files
+  %F{13}-c%f, %F{13}--commit%f    List commit and edit the selected commit through interactive rebase"
 }
 
+local -a selected_files
+local edit_type selected_commit
 edit_type="all"
-typeset -a selected_files && selected_files=()
-selected_commit=""
 
-while [[ "$#" -gt 0 ]]; do
+while (( $# )) {
   case "$1" in
-    -m|--modified) edit_type="modified"; shift ;;
-    -c|--commit) edit_type="commit";     shift ;;
-    -h|--help) usage && exit 0 ;;
-    *) echo "Invalid option: $1" >&2 && usage && exit 1 ;;
+    (-m|--modified) edit_type="modified"; shift  ;;
+    (-c|--commit)   edit_type="commit";   shift  ;;
+    (-h|--help)     usage;                exit 0 ;;
+    (*)             print::error "Invalid option: $1" && { usage; exit 1 } ;;
   esac
-done
+}
 
-if [[ "${edit_type}" == "commit" ]]; then
+if [[ "$edit_type" == commit ]]; then
   selected_commit=$(get_commit "select a commit to edit")
-  [[ -z "${selected_commit}" ]] && exit 1
-  git rebase -i "${selected_commit}"~
+  [[ -z "$selected_commit" ]] && exit 1
+  command git rebase -i "$selected_commit"~
 else
-  while IFS= read -r line; do
-    selected_files+=("${line}")
-  done < <(
-    if [[ "${edit_type}" == "modified" ]]; then
-      get_modified_file "select files to edit"
-    else
-      get_git_file "select files to edit"
-    fi
-  )
-  [[ "${#selected_files[@]}" -eq 0 ]] && exit 1
-  exec "${EDITOR}" "${selected_files[@]}"
+  if [[ "$edit_type" = modified ]] {
+    selected_files=( ${(@f)"$(get_modified_file 'select files to edit')"} )
+  } else {
+    selected_files=( ${(@f)"$(get_git_file 'select files to edit')"})
+  }
+
+  (( $#selected_files )) || exit 1
+  exec "$EDITOR" "$selected_files[@]"
 fi
diff --git a/flog b/flog
--- a/flog
+++ b/flog
@@ -1,5 +1,8 @@
-#!/usr/bin/env bash
-#
+#!/usr/bin/env zsh
+
+0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
+0="${${(M)0:#/*}:-$PWD/$0}"
+
 # Desc: git log interactive viewer
 #
 # @params
@@ -16,26 +19,29 @@
 #   -c|--checkout: checkout selected commmit
 #   -y|--yes: confirm action by default and skip confirmation
 
-set -ef
+emulate -LR zsh
+setopt warncreateglobal noshortloops
 
-mydir="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
-source "${mydir}"/fgit_helper.sh
+local mydir; mydir=${0:h:A}
+builtin source ${mydir}/fgit_helper
 
-usage() {
-  echo -e "Usage: flog [-h] [-r] [-R] [-e] [-c] [-y] ...
+function usage() {
+  builtin print -P -- "\
+%F{1}%BUsage%b%f:
+  %F{2}flog%f [%F{13}-h%f] [%F{13}-r%f] [%F{13}-R%f] [%F{13}-e%f] [%F{13}-c%f] [%F{13}-y%f] ...
 
 Interactive log viewer with action menu.
 Action menu contains options including revert|reset|edit|checkout|exit.
 
-Default: list all commits and prompt a menu to select action to perform.
+%F{4}Default%f: list all commits and prompt a menu to select action to perform.
 
-Optional arguments:
-  -h, --help\t\tshow this help message and exit.
-  -r, --revert\t\trevert the selected commit and skip action menu.
-  -R, --reset\t\treset HEAD back to selected commit and skip action menu.
-  -e, --edit\t\tedit selected commit through interactive rebase and skip action menu.
-  -c, --checkout\tcheckout selected commit and skip action menu.
-  -y, --yes\t\tacknowledge all actions that will be taken and skip confirmation."
+%F{1}%BOptions%f%b:
+  %F{13}-h%f, %F{13}--help%f     Show this help message and exit
+  %F{13}-r%f, %F{13}--revert%f   Revert the selected commit and skip action menu
+  %F{13}-R%f, %F{13}--reset%f    Reset HEAD back to selected commit and skip action menu
+  %F{13}-e%f, %F{13}--edit%f     Edit selected commit through interactive rebase and skip action menu
+  %F{13}-c%f, %F{13}--checkout%f Checkout selected commit and skip action menu
+  %F{13}-y%f, %F{13}--yes%f      Acknowledge all actions that will be taken and skip confirmation"
 }
 
 #######################################
@@ -46,71 +52,69 @@ Optional arguments:
 # Outputs:
 #   ${selected_action}: user selected action
 #######################################
-draw_menu() {
+function draw_menu() {
   local selected_commit="$1"
   local selected_action="$2"
   local menu header message
-  if [[ -n "$selected_action" ]]; then
-    echo "${selected_action}"
-  else
+  [[ -n "$selected_action" ]] && {
+    builtin print -r -- "$selected_action"
+  } || {
     menu="revert: revert the selected commit\n"
     menu="${menu}reset: reset HEAD to the selected commit using --mixed flag\n"
     menu="${menu}edit: edit selected commit through interactive rebase\n"
     menu="${menu}checkout: checkout the selected commit\n"
     menu="${menu}exit: quit flog"
     message=$(
-      git \
-      log --format=%B -n 1 "${selected_commit}"
+      command git log \
+        --format=%B -n 1 "$selected_commit"
     )
-    header="commit ${selected_commit}: ${message}"
-    selected_action=$(echo -e "${menu}" \
-      | fzf --no-multi --header="${header}" \
-      | awk -F ":" '{
+    header="commit $selected_commit: $message"
+    selected_action=$(print -- "$menu" \
+      | fzf --no-multi --header="$header" \
+      | command awk -F ":" '{
           print $1
         }'
     )
-    echo "${selected_action}"
-  fi
+    builtin print -r -- "$selected_action"
+  }
 }
 
-selected_action=""
-selected_commit=""
-confirm=""
-
-while [[ "$#" -gt 0 ]]; do
+while (( $# )) {
   case "$1" in
-    -r|--revert) selected_action="revert"; shift ;;
-    -R|--reset) selected_action="reset";   shift ;;
-    -e|--edit) selected_action="edit";     shift ;;
-    -c|--checkout) selected_action="checkout"; shift ;;
-    -y|--yes) confirm='y'; shift ;;
-    -h|--help) usage && exit 0 ;;
-    *) echo "Invalid option: $1" >&2 && usage && exit 1 ;;
+    (-r|--revert)   selected_action="revert";   shift ;;
+    (-R|--reset)    selected_action="reset";    shift ;;
+    (-e|--edit)     selected_action="edit";     shift ;;
+    (-c|--checkout) selected_action="checkout"; shift ;;
+    (-y|--yes)      confirm='y';                shift ;;
+    (-h|--help)     usage && exit 0 ;;
+    (*)             print::error "Invalid option: $1" &&   { usage; exit 1 } ;;
   esac
-done
+}
 
 while :; do
   selected_commit=$(get_commit)
-  [[ -z "${selected_commit}" ]] && exit 1
+  [[ -z "$selected_commit" ]] && exit 1
   selected_action=$(draw_menu "${selected_commit}" "${selected_action}")
-  [[ -n "${selected_action}" ]] && break
+  [[ -n "$selected_action" ]] && break
 done
 
 if [[ "${selected_action}" != 'exit' ]]; then
   if [[ "${selected_action}" == "reset" ]] && [[ -z "${confirm}" ]]; then
-    echo "(dryrun) reset HEAD to ${selected_commit}"
-  elif [[ -z "${confirm}" ]]; then
-    echo "(dryrun) ${selected_action} ${selected_commit}"
+    print -P -- "(%F{3}dryrun%f) reset HEAD to $selected_commit"
+  elif [[ -z "$confirm" ]]; then
+    print -P -- "(%F{3}dryrun%f) ${selected_action} ${selected_commit}"
   fi
-  [[ -z "${confirm}" ]] && confirm=$(get_confirmation)
-  [[ "${confirm}" != 'y' ]] && exit 1
+
+  [[ -z "$confirm" ]] && confirm=$(get_confirmation)
+  [[ "$confirm" != y ]] && exit 1
+  notify-send 'past'
 fi
 
-case "${selected_action}" in
-  revert) git revert "${selected_commit}" ;;
-  reset) git reset "${selected_commit}" ;;
-  edit) git rebase -i "${selected_commit}"~ ;;
-  checkout) git checkout "${selected_commit}" ;;
-  exit) exit 0 ;;
-  *) exit 1 ;;
-esac
+case "$selected_action" {
+  (revert) git revert "${selected_commit}" ;;
+  (reset) git reset "${selected_commit}" ;;
+  (edit) git rebase -i "${selected_commit}"~ ;;
+  (checkout) git checkout "${selected_commit}" ;;
+  (exit) exit 0 ;;
+  (*) exit 1 ;;
+}
diff --git a/freset b/freset
--- a/freset
+++ b/freset
@@ -1,5 +1,8 @@
-#!/usr/bin/env bash
-#
+#!/usr/bin/env zsh
+
+0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
+0="${${(M)0:#/*}:-$PWD/$0}"
+
 # Desc: unstage selected staged file || reset the commit to certain point
 #
 # @params
@@ -17,54 +20,55 @@
 #   -H|--hard: use --hard flag
 #   -y|--yes: confirm action by default and skip confirmation
 
-set -ef
+emulate -LR zsh
+setopt warncreateglobal noshortloops
 
-mydir="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
-source "${mydir}"/fgit_helper.sh
+local mydir; mydir=${0:h:A}
+builtin source ${mydir}/fgit_helper
 
-usage() {
-  echo -e "Usage: freset [-h] [-c] [-S] [-H] [-y] ...
+function usage() {
+  builtin print -P -- "\
+%F{1}%BUsage%f%b: %F{2}freset%f [%F{13}-h%f] [%F{13}-c%f] [%F{13}-S%f] [%F{13}-H%f] [%F{13}-y%f] ...
 
 Reset(unstage) the selected staged files.
 Reset the HEAD to certain commits by using -c flag.
 
-Default: unstage the selected files.
+%F{4}Default%f: unstage the selected files.
 
-Optional arguments:
-  -h, --help\t\tshow this help message and exit.
-  -c, --commit\t\treset HEAD to certain commit, default --mixed flag, reset HEAD to certain commit put all changes into modified state.
-  -S, --soft\t\treset commit using --soft flag, reset HEAD to certain commit without modify working tree.
-  -H, --hard\t\treset commit using --hard flag, reset HEAD to certain commit discard all changes from the working tree.
-  -y, --yes\t\tacknowledge all actions that will be taken and skip confirmation."
+%F{1}%BOptions%f%b:
+  %F{13}-h%f, %F{13}--help%f   Show this help message and exit
+  %F{13}-c%f, %F{13}--commit%f Reset HEAD to certain commit
+               %F{4}Default%f: --mixed flag, reset HEAD to certain commit put all changes into modified state
+  %F{13}-S%f, %F{13}--soft%f   Reset commit using --soft flag, reset HEAD to certain commit without modify working tree
+  %F{13}-H%f, %F{13}--hard%f   Reset commit using --hard flag, reset HEAD to certain commit discard all changes from the working tree
+  %F{13}-y%f, %F{13}--yes%f    Acknowledge all actions that will be taken and skip confirmation"
 }
 
+local reset_option reset_type
+local -a selected_files
 reset_option="--mixed"
 reset_type="modified"
-typeset -a selected_files && selected_files=()
-confirm=""
-selected_commit=""
 
-while [[ "$#" -gt 0 ]]; do
+while (( $# )) {
   case "$1" in
-    -c|--commit) reset_type="commit"; shift ;;
-    -S|--soft) reset_option="--soft"; shift ;;
-    -H|--hard) reset_option="--hard"; shift ;;
-    -y|--yes) confirm='y'; shift ;;
-    -h|--help) usage && exit 0 ;;
-    *) echo "Invalid option: $1" >&2 && usage && exit 1 ;;
+    (-c|--commit) reset_type="commit";   shift   ;;
+    (-S|--soft)   reset_option="--soft"; shift   ;;
+    (-H|--hard)   reset_option="--hard"; shift   ;;
+    (-y|--yes)    confirm='y';           shift   ;;
+    (-h|--help)   usage;                 exit 0  ;;
+    (*)           print::error "Invalid option: $1" && { usage; exit 1 } ;;
   esac
-done
+}
 
-if [[ "${reset_type}" == "commit" ]]; then
-  selected_commit=$(get_commit "select the target commit")
-  [[ -z "${selected_commit}" ]] && exit 1
-  [[ -z "${confirm}" ]] && confirm=$(get_confirmation "Reset HEAD to ${selected_commit} ${reset_option}?")
-  [[ "${confirm}" != 'y' ]] && exit 1
-  git reset "${selected_commit}" "${reset_option}"
+if [[ "$reset_type" = "commit" ]]; then
+  selected_commit=$(get_commit "Select the target commit")
+  [[ -z "$selected_commit" ]] && exit 1
+  [[ -z "$confirm" ]] && confirm=$(get_confirmation "Reset HEAD to $selected_commit $reset_option?")
+  [[ "$confirm" != y ]] && exit 1
+  command git reset "$selected_commit" "$reset_option"
 else
-  while IFS= read -r line; do
-    selected_files+=("${line}")
-  done < <(get_modified_file 'select files to unstage' 'staged')
-  [[ "${#selected_files[@]}" -eq 0 ]] && exit 1
-  git reset "${selected_files[@]}"
+  selected_files=( ${(@f)"$(get_modified_file 'select files to unstage' 'staged')"} )
+  (( $#selected_files )) || exit 1
+  command git reset "${selected_files[@]}"
+
 fi
diff --git a/fstash b/fstash
--- a/fstash
+++ b/fstash
@@ -1,5 +1,8 @@
-#!/usr/bin/env bash
-#
+#!/usr/bin/env zsh
+
+0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
+0="${${(M)0:#/*}:-$PWD/$0}"
+
 # Desc: stash operation using fzf
 #
 # @params
@@ -15,64 +18,67 @@
 #   -d|--delete: delete selected stash
 #   -p|--pop: use pop instead of apply on the selected stash
 
-set -ef
+emulate -LR zsh
+setopt warncreateglobal noshortloops
 
-mydir="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
-source "${mydir}"/fgit_helper.sh
+local mydir; mydir=${0:h:A}
+builtin source ${mydir}/fgit_helper
 
-usage() {
-  echo -e "Usage: fstash [-h] [-s] [-d] [-p] ...
+function usage() {
+  builtin print -P -- "\
+%F{1}%BUsage%f%b: %F{2}fstash%f [%F{13}-h%f] [%F{13}-s%f] [%F{13}-d%f] [%F{13}-p%f] ...
 
 View and manage stash interactively.
 
-Default: list all stashes and apply the selected stash.
+%F{4}Default%f: list all stashes and apply the selected stash.
 
-Optional arguments:
-  -h, --help\t\tshow this help message and exit.
-  -s, --select\t\tlist modified files and stash the selected files.
-  -d, --delete\t\tlist all stashes and delete the selected stash from stash list.
-  -p, --pop\t\tuse 'stash pop' instead of 'stash apply'."
+%F{1}%BOptions%f%b:
+  %F{13}-h%f, %F{13}--help%f    Show this help message and exit
+  %F{13}-s%f, %F{13}--select%f  List modified files and stash the selected files
+  %F{13}-d%f, %F{13}--delete%f  List all stashes and delete the selected stash from stash list
+  %F{13}-p%f, %F{13}--pop%f     Use 'stash pop' instead of 'stash apply'"
 }
 
+local stash_command confirm
+local -a selected_files selected_stash
 stash_command="apply"
-typeset -a selected_files && selected_files=()
-selected_stash=""
-confirm=""
 
-while [[ "$#" -gt 0 ]]; do
+while (( $# )) {
   case "$1" in
-    -p|--pop) stash_command="pop";       shift ;;
-    -s|--select) stash_command="select"; shift ;;
-    -d|--delete) stash_command="delete"; shift ;;
-    -y|--yes) confirm="y"; shift ;;
-    -h|--help) usage && exit 0 ;;
-    *) echo "Invalid option: $1" >&2 && usage && exit 1 ;;
+    (-p|--pop)    stash_command="pop";    shift ;;
+    (-s|--select) stash_command="select"; shift ;;
+    (-d|--delete) stash_command="delete"; shift ;;
+    (-y|--yes)    confirm="y";            shift ;;
+    (-h|--help)   usage; exit 0  ;;
+    (*)           print::error "Invalid option: $1" && { usage; exit 1 } ;;
   esac
-done
+}
 
-if [[ "${stash_command}" == "select" ]]; then
-  while IFS= read -r line; do
-    selected_files+=("${line}")
-  done < <(get_modified_file "select files to add to a stash")
-  [[ "${#selected_files[@]}" -eq 0 ]] && exit 1
-  git stash -- "${selected_files[@]}"
-elif [[ "${stash_command}" == "delete" ]]; then
-  selected_stash=$(get_stash "select stash to delete")
-  [[ -z "${selected_stash}" ]] && exit 1
-  [[ -z "${confirm}" ]] && \
-    while IFS= read -r line; do
-      echo "(dryrun) drop ${line}"
-    done <<< "${selected_stash}"
-  [[ -z "${confirm}" ]] && confirm=$(get_confirmation)
-  [[ "${confirm}" != 'y' ]] && exit 1
-  while IFS= read -r line; do
-    git stash drop "${line}"
-  done <<< "${selected_stash}"
+local line
+
+if [[ "$stash_command" == "select" ]]; then
+  selected_files=( ${(@f)"$(get_modified_file "select files to add to a stash")"} )
+  (( $#selected_files )) || exit 1
+  command git stash -- "$selected_files[@]"
+elif [[ "$stash_command" == "delete" ]]; then
+  selected_stash=( ${(@f)"$(get_stash 'select stash to delete')"} )
+  (( $#selected_stash )) || exit 1
+  [[ -z "$confirm" ]] && \
+    foreach line ("$selected_stash[@]") {
+      print -P -- "(%F{3}dryrun%f) drop ${line}"
+    }
+
+  [[ -z "$confirm" ]] && confirm=$(get_confirmation)
+  [[ "$confirm" != y ]] && exit 1
+
+  foreach line ("$selected_stash[@]") {
+    command git stash drop "${line}"
+  }
 else
-  selected_stash=$(get_stash "select stash to apply" "true")
-  [[ -z "${selected_stash}" ]] && exit 1
-  [[ -z "${confirm}" ]] && echo "(dryrun) ${stash_command} ${selected_stash}"
-  [[ -z "${confirm}" ]] && confirm=$(get_confirmation)
-  [[ "${confirm}" != 'y' ]] && exit 1
-  git stash "${stash_command}" "${selected_stash}"
+  selected_stash=( ${(@f)"$(get_stash 'select stash to apply' 'true')"} )
+  (( $#selected_stash )) || exit 1
+  [[ -z "$confirm" ]] && print -P -- "(%F{3}dryrun%f) $stash_command $selected_stash"
+  [[ -z "$confirm" ]] && confirm=$(get_confirmation)
+  [[ "$confirm" != y ]] && exit 1
+  command git stash "$stash_command" "$selected_stash"
 fi
